---
version: '3.5' 

networks:
  confluent-prod:
    name: confluent-prod

services: 
  ldap:
    image: geerlingguy/docker-centos7-ansible
    hostname: ldap.prod.confluent
    container_name: ldap.prod.confluent
    networks:
      - confluent-prod
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  zk1:
    image: cnfltraining/ansible:7.2
    hostname: zk1.prod.confluent
    container_name: zk1.prod.confluent
    networks:
      - confluent-prod
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  kafka-0:
    image: cnfltraining/ansible:7.2
    hostname: kafka-0.prod.confluent
    container_name: kafka-0.prod.confluent
    networks:
      - confluent-prod
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  kafka-1:
    image: cnfltraining/ansible:7.2
    hostname: kafka-1.prod.confluent
    container_name: kafka-1.prod.confluent
    networks:
      - confluent-prod
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  kafka-2:
    image: cnfltraining/ansible:7.2
    hostname: kafka-2.prod.confluent
    container_name: kafka-2.prod.confluent
    networks:
      - confluent-prod
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  schema-registry:
    image: cnfltraining/ansible:7.2
    hostname: schema-registry.prod.confluent
    container_name: schema-registry.prod.confluent
    networks:
      - confluent-prod
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  control-center:
    image: cnfltraining/ansible:7.2
    hostname: control-center.prod.confluent
    container_name: control-center.prod.confluent
    networks:
      - confluent-prod
    privileged: true
    ports:
      - "9021:9021"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  kafka-connect:
    image: cnfltraining/ansible:7.2
    hostname: kafka-connect.prod.confluent
    container_name: kafka-connect.prod.confluent
    networks:
      - confluent-prod
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  ksqldb:
    image: cnfltraining/ansible:7.2
    hostname: ksqldb.prod.confluent
    container_name: ksqldb.prod.confluent
    networks:
      - confluent-prod
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro